// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/about.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/github/[username].tsx";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/FloatingActionButton.tsx";
import * as $$1 from "./islands/Form.tsx";
import * as $$2 from "./islands/Header.tsx";
import * as $$3 from "./islands/Plan.tsx";
import * as $$4 from "./islands/Plans.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/about.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/github/[username].tsx": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/FloatingActionButton.tsx": $$0,
    "./islands/Form.tsx": $$1,
    "./islands/Header.tsx": $$2,
    "./islands/Plan.tsx": $$3,
    "./islands/Plans.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
